version: "3.8"

services:
  db:
    image: postgres:14
    volumes:
      - data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=blog_app
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    networks:
      - nw_pyblog
    container_name: blogpy_db

  blog:
    build:
      dockerfile: Dockerfile
      context: .
    image: gilsonjr/blogpy:1.0
    container_name: blogpy
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 80:8000
    networks:
      - nw_pyblog
    volumes:
      - app:/var/www/
    depends_on:
      - db

networks:
  nw_pyblog:
    driver: bridge

volumes:
  app:
  data: